### ISSUE TITLE
Find Romanian border guard website links

### ISSUE THREAD

**Issue by EchoRuby68** [Ukraine-Relief-Efforts/scraper#7]

**Comment by NeoBushido42** [comment]
https://www.politiadefrontiera.ro/en/main/home.html

**Comment by marcbak** [comment]
https://romania.iom.int/news/useful-information-people-entering-romania-ukraine

**Comment by Aziroshin** [comment]
- Interactive map with border crossings and wait times in the placemarker pop-ups: https://www.politiadefrontiera.ro/en/traficonline/?dt=1
- Another map with border crossing points, but instead of wait times the pop-ups have a button which opens a website (in a new tab) with a bit of info about the checkpoint, including a phone number: https://www.politiadefrontiera.ro/en/main/pg-border-crossing-points-88.html
- Some document I found regarding the situation. It mostly seems to be concerned with the COVID-19 exceptions in this context (I don't speak Romanian, so I had to glean things from a google translation): https://www.politiadefrontiera.ro/files/docu/1645787196157-hcnsunr9din25022022final.pdf

**Comment by Jachdich** [comment]
Fixed in #42
